### ISSUE TITLE
Allow users to rotate the 3D visualization

### ISSUE THREAD

**Issue by schuemie** [michip/collabovid#16]
It seems most of the variance is in the Z-axis (perpendicular to the screen)? Allowing smooth rotation may help users better interpret the 3D structure.

**Comment by jonasd4** [comment]
@schuemie Yes, you are absolutely right. Allowing rotation would help to discover the depth of the visualization. We already experimented with allowing rotation in the view, but it felt rather confusing when navigating and it was hard to navigate to individual papers with mouse controls. So we did not release it yet. We will look how to make it more usable and then add it to the website.

**Comment by michip** [comment]
The requested feature is now available.
