### ISSUE TITLE
Allow searching for a specific article in the 3D visualization

### ISSUE THREAD

**Issue by schuemie** [michip/collabovid#17]
It might be helpful to find a specific article (e.g. the one you authored), and see what other articles are in the same 'cluster', and to see what related 'clusters' are.

**Comment by michip** [comment]
@schuemie Thank you for your suggestions. It is already possible to highlight a specific article in the 3D visualization. When you search for a paper you will find a link "visualize" in the bottom right corner that redirects you to the embedding with the highlighted paper. As for now, we allow users to browse all papers in a cluster by clicking on the "View all papers" link. We plan to make the papers within a cluster and cluster neighborhoods easier to access in the near future.
